### ISSUE TITLE
Apperance of Windows Buttons is Broken

### ISSUE THREAD

**Issue by rumphelstilskin** [Fausto-Korpsvart/Gruvbox-GTK-Theme#88]
![Image](https://github.com/user-attachments/assets/154d6266-0079-4b4d-aa0c-e28b11aeb3e5)
I installed Arch linux and gnome yesterday. Windows buttons of some gnome apps like nautilus, tweaks, etc is looking weird. Can you help me to fix it?

**Comment by rumphelstilskin** [comment]
Yes i didnt install from github repo. I installed from gnome-look.org. I will try to install from this repo.

**Comment by rumphelstilskin** [comment]
Sorry mate i didn't see any file links on release page. Where can i download theme? I always download gnome-look.org :)

**Comment by Fausto-Korpsvart** [comment]
> Sorry mate i didn't see any file links on release page. Where can i download theme? I always download gnome-look.org :)

You need to install from the terminal, all the installation information is in the README.

I will update the themes in gnome-look soon.

**Comment by Fausto-Korpsvart** [comment]
> I did the installation procedure via repository and the problem reported by the colleague continues, I could not identify how to adjust it.

Tell me the distro you use to get an idea, I've tried on several distros and the bug is already fixed, it's possible that you should do a GTK update, because the distros I've tried are fully updated.

**Comment by FGYada1984** [comment]
> > I did the installation procedure via repository and the problem reported by the colleague continues, I could not identify how to adjust it.
> 
> Tell me the distro you use to get an idea, I've tried on several distros and the bug is already fixed, it's possible that you should do a GTK update, because the distros I've tried are fully updated.

I use Arch and everything is up to date, at least there's nothing pending.

**Comment by Fausto-Korpsvart** [comment]
> I use Arch and everything is up to date, at least there's nothing pending.

When I have some time I will check again and test, because as far as I have tested the problem was solved some time ago.

Thanks for reporting.

**Comment by rodude123** [comment]
@Fausto-Korpsvart Problem still persists, anything I can do about it?

![Image](https://github.com/user-attachments/assets/529baae8-89c7-4420-9336-321b1aa681bb)

**Comment by rumphelstilskin** [comment]
Hey FGYada1984!
I try to find this block in gtk.css or gtk-dark.css. But i couldnt. Can you send me file that you edit?

**Comment by FGYada1984** [comment]
> Hey FGYada1984! I try to find this block in gtk.css or gtk-dark.css. But i couldnt. Can you send me file that you edit?


just add to the end of your gtk-dark.css and/or gtk.css file inside the .config/gtk-4.0 folder. Anyway, I put on pastebin the complete copy of how mine is (but it's important to note that there are some more changes I made that meet my needs). I hope it helps you.

https://pastebin.com/0UtVjtq7

**Comment by Fausto-Korpsvart** [comment]
> Hello Fausto,
> 
> I managed to find a solution to style the window control buttons correctly. It seems the default GNOME Shell styles were a bit persistent and needed to be forcefully reset.
> 
> The fix is to replace the existing windowcontrols button block in both gtk-4.0/gtk.css and gtk-4.0/gtk-dark.css files with the following code. The key was to use all: unset !important; to reset GNOME's default styling before applying the new rules.

Thanks for the tip, now that I have started to fix bugs in the themes, I will take this into account to fix it as soon as possible.

I find it quite strange that I have been testing on Arch Linux, both pure and Manjaro, both updated and the error doesn't appear, I don't know what this error is due to, as I can't reproduce it on clean installs.

Anyway, if I manage to reproduce the error, I will see how your solutions work, I will also check the base theme, Magnetic GTK theme, to see on that side they have already solved it, as the solutions I added in some previous commits caused the title bar to increase its size in some applications, so I want to find a solution that does not affect the theme in general by solving the problem.

Thanks again for the tip and for helping the project.
